name: tp_dart_client
description: Un client Dart pour l'API de gestion de produits et commandes
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.12.0 <3.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
    http: ^0.13.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

  executables:
  tp_dart_client:
  script: tp_dart_client.dart
