name: tp_dart_client

description: A simple API client in Dart



environment:

  sdk: ">=2.12.0 <3.0.0"



dependencies:

  http: ^1.3.0



dev_dependencies:

  lints: ^5.0.0

  test: ^1.24.0



exécutables:

  tp_dart_client:

    script: tp_dart_client.dart